### ISSUE TITLE
Does not show correct errors

### ISSUE THREAD

**Issue by sandip-mane** [bigbinary/org_incineration#53]
Here, the actual exception is:
```
PG::ForeignKeyViolation: ERROR:  update or delete on table "neeto_rules" violates foreign key constraint "core_actions_rule_id_fk" on table "neeto_rules_actions"
DETAIL:  Key (id)=(776c53c2-0b93-4a65-aab4-25d7195dfc8f) is still referenced from table "neeto_rules_actions".
```

But it shows the following:
```
ERROR OrganizationTest#test_that_organization_is_incinerated (1.33s)
Minitest::UnexpectedError:         ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block

            activerecord (6.1.5.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `block (2 levels) in query'
            activesupport (6.1.5.1) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
            activesupport (6.1.5.1) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
            activesupport (6.1.5.1) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
            activesupport (6.1.5.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
            activesupport (6.1.5.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
            activesupport (6.1.5.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
            activesupport (6.1.5.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
            activesupport (6.1.5.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
            activesupport (6.1.5.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/postgresql_adapter.rb:820:in `column_definitions'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `columns'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/schema_cache.rb:112:in `block in columns'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/schema_cache.rb:111:in `fetch'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/schema_cache.rb:111:in `columns'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/schema_cache.rb:120:in `block in columns_hash'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/schema_cache.rb:119:in `fetch'
            activerecord (6.1.5.1) lib/active_record/connection_adapters/schema_cache.rb:119:in `columns_hash'
            activerecord (6.1.5.1) lib/active_record/model_schema.rb:553:in `load_schema!'
            activerecord (6.1.5.1) lib/active_record/attributes.rb:250:in `load_schema!'
            activerecord (6.1.5.1) lib/active_record/model_schema.rb:539:in `block in load_schema'
            activerecord (6.1.5.1) lib/active_record/model_schema.rb:536:in `synchronize'
            activerecord (6.1.5.1) lib/active_record/model_schema.rb:536:in `load_schema'
            activerecord (6.1.5.1) lib/active_record/model_schema.rb:402:in `attribute_types'
            activerecord (6.1.5.1) lib/active_record/attribute_methods.rb:187:in `_has_attribute?'
            activerecord (6.1.5.1) lib/active_record/inheritance.rb:57:in `new'
            activerecord (6.1.5.1) lib/active_record/persistence.rb:37:in `create'
            /Users/sandipmane/Work/BigBinary/org_incineration/lib/org_incineration.rb:28:in `run!'
            app/models/concerns/incinerable_concern.rb:12:in `incinerate!'
            test/models/organization_test.rb:73:in `block in test_that_organization_is_incinerated'
            activesupport (6.1.5.1) lib/active_support/testing/assertions.rb:34:in `assert_nothing_raised'
            activesupport (6.1.5.1) lib/active_support/testing/assertions.rb:102:in `assert_difference'
            test/models/organization_test.rb:72:in `test_that_organization_is_incinerated'
            minitest (5.16.0) lib/minitest/test.rb:98:in `block (3 levels) in run'
            minitest (5.16.0) lib/minitest/test.rb:195:in `capture_exceptions'
            minitest (5.16.0) lib/minitest/test.rb:95:in `block (2 levels) in run'
            minitest (5.16.0) lib/minitest.rb:296:in `time_it'
            minitest (5.16.0) lib/minitest/test.rb:94:in `block in run'
            minitest (5.16.0) lib/minitest.rb:391:in `on_signal'
            minitest (5.16.0) lib/minitest/test.rb:236:in `with_info_handler'
            minitest (5.16.0) lib/minitest/test.rb:93:in `run'
            minitest-reporters (1.5.0) lib/minitest/reporters.rb:48:in `run_with_hooks'
            minitest (5.16.0) lib/minitest.rb:1059:in `run_one_method'
            minitest (5.16.0) lib/minitest.rb:365:in `run_one_method'
            minitest (5.16.0) lib/minitest.rb:352:in `block (2 levels) in run'
            minitest (5.16.0) lib/minitest.rb:351:in `each'
            minitest (5.16.0) lib/minitest.rb:351:in `block in run'
            minitest (5.16.0) lib/minitest.rb:391:in `on_signal'
            minitest (5.16.0) lib/minitest.rb:378:in `with_info_handler'
            minitest (5.16.0) lib/minitest.rb:350:in `run'
            railties (6.1.5.1) lib/rails/test_unit/line_filtering.rb:10:in `run'
            minitest (5.16.0) lib/minitest.rb:182:in `block in __run'
            minitest (5.16.0) lib/minitest.rb:182:in `map'
            minitest (5.16.0) lib/minitest.rb:182:in `__run'
            minitest (5.16.0) lib/minitest.rb:159:in `run'
            minitest (5.16.0) lib/minitest.rb:83:in `block in autorun'
            activesupport (6.1.5.1) lib/active_support/fork_tracker.rb:8:in `fork'
            activesupport (6.1.5.1) lib/active_support/fork_tracker.rb:8:in `fork'
            activesupport (6.1.5.1) lib/active_support/fork_tracker.rb:27:in `fork'
            activesupport (6.1.5.1) lib/active_support/fork_tracker.rb:8:in `fork'
            activesupport (6.1.5.1) lib/active_support/fork_tracker.rb:27:in `fork'
            <internal:/Users/sandipmane/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
            <internal:/Users/sandipmane/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
            -e:1:in `<main>'
```

**Comment by shreyansh-g24** [comment]
@sandip-mane When the incineration fails, it creates a record in `OrgIncineration::IncinerationRecord` with the exception raised.

Can you please check if the correct exception is being reflected in the record that is created?

---

Also the table is named `neeto_rules`. Does it originate from some gem/engine or a `neeto-web-app`?

**Comment by sandip-mane** [comment]
@shreyansh-g24 

> Also the table is named neeto_rules. Does it originate from some gem/engine or a neeto-web-app?

Yes, this table is from a gem [neeto-rules-engine](https://github.com/bigbinary/neeto-rules-engine).

> Can you please check if the correct exception is being reflected in the record that is created?

We noticed this in the test suit, I've also reset the data for it, please LMK if you need me to reproduce it and share this info.

**Comment by shreyansh-g24** [comment]
Cool, no need. Please check here and add an `incinerable_concern.rb` for the engine, this issue will be fixed with this. https://github.com/bigbinary/org_incineration/pull/51#issuecomment-1158491699
